version: "3.9"
services:
  webapp:
    build: .
    command: npm run watch
    depends_on:
       - redis
    ports:
      - 8000:8080
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 8080      
  redis:
    image: redis:alpine
