name: nodeapp-ci

on:
  push:
    branches: 
     - main
     - feature/github-actions
  pull_request:
    branches:
     - main     

jobs:

  build-test-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: myrestnodeapp
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      IMAGE_REGISTRY: ghcr.io
      USER_NAME: ${{ github.actor }}

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}      
  
    - name: Build the Image
      run:
        docker build --tag $IMAGE_REGISTRY/$USER_NAME/$IMAGE_NAME:$IMAGE_TAG .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: ${{ env.IMAGE_REGISTRY }}/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'        

    - name: Test the application 
      id: test
      run:
        docker run $IMAGE_REGISTRY/$USER_NAME/$IMAGE_NAME:$IMAGE_TAG npm run test      
        
    - name: Push the image
      run: 
       docker push $IMAGE_REGISTRY/$USER_NAME/$IMAGE_NAME:$IMAGE_TAG
      if: steps.test.outcome == 'success'
